### ISSUE TITLE
无法正常工作

### ISSUE THREAD

**Issue by magichowl** [tumashu/bbdb-handy#1]
无论是 easiest way or  manual way 都无法正常工作　debug-init的结果如下

```
Debugger entered--Lisp error: (void-variable message-mode-map)
  bbdb-handy-enable()
  eval-buffer(#<buffer  *load*-293715> nil "/home/pan/.emacs.d/lisp/init-bbdb.el" nil t)  ; Reading at buffer position 13034
  load-with-code-conversion("/home/pan/.emacs.d/lisp/init-bbdb.el" "/home/pan/.emacs.d/lisp/init-bbdb.el" nil t)
  #<subr require>(init-bbdb nil nil)
  ad-Advice-require(#<subr require> init-bbdb)
  apply(ad-Advice-require #<subr require> init-bbdb)
  require(init-bbdb)
  eval-buffer(#<buffer  *load*-597015> nil "/home/pan/.emacs.d/lisp/init-loadpackages.el" nil t)  ; Reading at buffer position 1606
  load-with-code-conversion("/home/pan/.emacs.d/lisp/init-loadpackages.el" "/home/pan/.emacs.d/lisp/init-loadpackages.el" nil nil)
  load("~/.emacs.d/lisp/init-loadpackages.el")
  eval-buffer(#<buffer  *load*> nil "/home/pan/.emacs.d/init.el" nil t)  ; Reading at buffer position 1290
  load-with-code-conversion("/home/pan/.emacs.d/init.el" "/home/pan/.emacs.d/init.el" t t)
  load("/home/pan/.emacs.d/init" t t)
  #[0 "\205\262
```
我尝试把自己的bbdb配置都删除，　只留下bbdb-handy 的配置 还是不行

如果我在emacs 运行后, eval
(bbdb-handy-enable)

提示为　BBDB-handy: Override BBDB keybindings: g, q, p, CTRL-s, b, CTRL-c CTRL-c, RET

在　To: 后输入联系人的拼音首字母，使用tab键后多出来一个window 叫"*BBDB*" 的buffer 里面有所有的联系人，没办法选择所需要的联系人及其邮件地址。

**Comment by tumashu** [comment]
第一个问题是因为，你运行bbdb-handy-enable在早，message没有加载，我已经提交了一个commit，在这个函数中强行加载message。

**Comment by tumashu** [comment]
第二个问题可能是你没有安装 bbdb-china 包， 拼音首字母搜索是依赖这个功能的，你看看你bbdb中中文联系人有没有      pinyin-abbrev:

**Comment by magichowl** [comment]
第一个问题已解决，　第二个问题还在，
我已经装有bbdb-china且中文联系人中都有拼音字段

在　To: 后输入联系人的拼音首字母，使用tab键后多出来一个window 叫"BBDB" 的buffer 里面有所有的联系人，当我再按照拼音首字母来搜索到我要的联系人后，

按下　回车　msg is:
Variable `bbdb-handy-push-buffer' set to `nil', Do nothing!!

按下　'p' 后，　msg is:
command-execute: Symbol's function definition is void: bbdb-handy-bbdb-push-mail

**Comment by tumashu** [comment]
```
按下　'p' 后，　msg is:
command-execute: Symbol's function definition is void: bbdb-handy-bbdb-push-mail
```
bug，已经修复

**Comment by tumashu** [comment]
```
在　To: 后输入联系人的拼音首字母，使用tab键后多出来一个window 叫"BBDB" 的buffer 里面有所有的联系人，当我再按照拼音首字母来搜索到我要的联系人后，

按下　回车　msg is:
Variable bbdb-handy-push-buffer' set tonil', Do nothing!!
```
弱弱的问一下，你用什么写邮件，目前这个功能暂时只在message中可以使用，mu4e也是用message写邮件吗？

**Comment by magichowl** [comment]
用的是　mu4e 写邮件，　

(mu4e-compose-mode)

Parent mode: `message-mode'.

我原有的配置是
(local-set-key "<TAB>" 'bbdb-complete-name)
产生的效果是　能通过name 或mail address 字段来自动补全mail address

现在tab 是触发的function "bbdb-handy-message-tab", 不但不能拼音补全，而且上述的两种补全也是出现我说的问题

**Comment by tumashu** [comment]
我明白了，我在bbdb-handy中。用(string= mode-name "Message")强制判断是否当前buffer是邮件buffer，我估计这个判断不适用于mu4e

**Comment by tumashu** [comment]
你的 mode-name 是什么？

**Comment by magichowl** [comment]
mu4e-compose-mode 它的parent mode 是　message-mode

**Comment by tumashu** [comment]
Updated, try again!

**Comment by magichowl** [comment]
version 20150707.626?  没有变化呀？

**Comment by tumashu** [comment]
刚刚提交到githhub，不可能这么快的。。。

**Comment by tumashu** [comment]
melpa更新估计的1个多小时，你可以直接git

https://github.com/tumashu/bbdb-handy

**Comment by magichowl** [comment]
ok, 我看别人在　comments 之间也会插入　commit 的信息以供查看　这样就知道到底改了没了～～

**Comment by magichowl** [comment]
果然是旧版本

**Comment by tumashu** [comment]
个人习惯吧，那么整比较麻烦，懒的折腾。。。

**Comment by tumashu** [comment]
同学尽量试试吧，明天我就出门了，估计两个星期不能折腾emacs。。。

**Comment by magichowl** [comment]
好的　我现在就看

**Comment by magichowl** [comment]
自动补全的问题基本没有，　只是出现了小意外
在bbdb中　一个联系人的多个mail 都是以“，”分隔的，　这点不像phone字段是分开存储的

               mail: we**g@vip.qq.com, w**ng@foxmail.com　

自动补全后，每次都只应用第一个邮箱地址，且补全结果如下
To: we**g@vip.qq.com,

注意，　多了一个逗号

导致收不到邮件

如把逗号删除，　邮件能正常收到

**Comment by tumashu** [comment]
想补全第二个邮件地址, 按C-u 2 RET，第三个C-u 3 RET

**Comment by tumashu** [comment]
逗号看起来挺简单，但我还没有没想到解决的好方法，我这里逗号似乎没问题，不知道什么情况。

**Comment by tumashu** [comment]
那个逗号是为了隔开多个人收件人的。。。

**Comment by tumashu** [comment]
再有其他问题，新开一个帖子吧，这个太长了。。。

**Comment by magichowl** [comment]
没问题了，我的hotmail收不到邮件了，　其它邮箱都正常，　thanks

**Comment by magichowl** [comment]
群发也正常，　hotmail终于收到了　延迟太大，　非常感谢！

**Comment by tumashu** [comment]
这个逗号确实让头一次使用bbdb-handy的同学感到困惑，我打算不插入这个逗号了，当发送到多个联系人时，由用户自己输入。。。

**Comment by tumashu** [comment]
现在逗号是按照需要插入了，同学可以试试。。。。

**Comment by magichowl** [comment]
是的　很智能呢
